### ISSUE TITLE
[PE-D][Tester A] Exception when paid a higher amount in addorder

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113T-T09-2/tp#238]
![image.png](https://raw.githubusercontent.com/DeepanjaliDhawan/ped/main/files/6098672b-cb6a-41c9-a81b-9aee569e0bc3.png)

When my subtotal was 29.50 and gave 50, the change was calculated correctly (20.50) and the order had been added as well but it gave me an exception and shut down the program making it unusable for us. 

But good job.. when I ran the program again, the menu remained intact.

Please consider either removing or modifying the exception...

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: DeepanjaliDhawan/ped#6

**Comment by sansders** [comment]
This tester used java 19 instead of java 11.

When our application is run with java 19.0.1, the user will receive the error message as shown by the tester.

We have done our checks, replicated this in java 19, and found that it only happens if the application is not run in java 11.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/20165093/229301608-dd3ba38a-9e63-4a6b-a5ce-5571bc4d7f1f.png)
